import { CSSProperties } from "react";
import "../styles/components/icon.css";

export const ICONS = Object.freeze({
    ADD: "add",
    ADD_CIRCLE: "add_circle",
    ARROW_DROP_DOWN: "arrow_drop_down",
    ARROW_DROP_UP: "arrow_drop_up",
    BED: "bed",
    BEDROOM_PARENT: "bedroom_parent",
    BUG_REPORT: "bug_report",
    BOOKMARK_STAR: "bookmark_star",
    CALENDAR_ADD_ON: "calendar_add_on",
    CANCEL: "cancel",
    CHECK: "check",
    CHECK_CIRCLE: "check_circle",
    CLOSE: "close",
    CLOUD_UPLOAD: "cloud_upload",
    CONTEXTUAL_TOKEN: "contextual_token",
    DELETE: "delete",
    DISABLED_BY_DEFAULT: "disabled_by_default",
    DO_NOT_DISTURB_ON: "do_not_disturb_on",
    EDIT: "edit",
    EDIT_SQUARE: "edit_square",
    ERROR: "error",
    FILE_OPEN: "file_open",
    FIND_IN_PAGE: "find_in_page",
    GROUPS: "groups",
    HELP: "help",
    HOME: "home",
    ID_CARD: "id_card",
    INFO: "info",
    KEY: "key",
    KEYBOARD_ARROW_LEFT: "keyboard_arrow_left",
    KEYBOARD_ARROW_RIGHT: "keyboard_arrow_right",
    LOCAL_ACTIVITY: "local_activity",
    LOCK: "lock",
    LOGOUT: "logout",
    MAIL: "mail",
    OPEN_IN_NEW: "open_in_new",
    PERSON: "person",
    PERSON_ADD: "person_add",
    PERSON_BOOK: "person_book",
    PETS: "pets",
    PHOTO_CAMERA: "photo_camera",
    PROGRESS_ACTIVITY: "progress_activity",
    REFRESH: "refresh",
    REMOVE: "remove",
    REPLAY: "replay",
    SEARCH:"search",
    SAVE: "save",
    SHOPPING_CART: "shopping_cart",
    VISIBILITY: "visibility",
    VISIBILITY_OFF: "visibility_off",
});

export default function Icon ({iconName, style, className}: Readonly<{
    iconName: string, style?: CSSProperties, className?: string;
}>) {
    return (<i className={`mdi ${className ?? ""}`} style={{...style}}>{iconName}</i>)
}